---
title: "Multivariate Modeling Methods (Spring 2026; Clemson University: EDF 9780)"
---

## Course Objectives

In this course, contemporary approaches to multivariate analysis with maximum likelihood and Bayesian methods are presented. Classical topics in multivariate analysis including multivariate analysis of variance and exploratory factor analysis, are covered in the context of mixed-effects models, preparing students for subsequent courses and research that use such model-based methods. Possible topics include extensions of linear models (regression and analysis of variance) for non-normal data with link functions, introductory matrix algebra, missing data modeling techniques, models for repeated measures data, and path analysis models for multivariate regression evaluating both moderation and mediation effects. Topics will be finalized after the first meeting of the course.

Note: The materials in this course were created by both myself and [Lesa Hoffman](https://www.lesahoffman.com) through years of collaboration. Materials created by Lesa are used with her permission.

## Course Readings

The course will provide all readings on our course Canvas site.

## Helpful R Links

| Resource                            | Link                           |
|-------------------------------------|--------------------------------|
| R for Data Science (Intro R E-book) | <https://r4ds.had.co.nz>       |
| Advanced R (next steps in R E-book) | <https://adv-r.hadley.nz>      |
| rig (R Installation Manager)        | <https://github.com/r-lib/rig> |

## Course Details

+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Instructor:              | Jonathan Templin                                                                                                                                          |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| email:                   | [jltempli\@clemson.edu](mailto:jltempli@clemson.edu)                                                                                                      |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course website:          | <https://jonathantemplin.github.io/Multivariate-Modeling-Spring-2026/>                                                                                    |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course repo:             | <https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026>                                                                                    |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course YouTube Playlist: | <https://www.youtube.com/playlist?list=PLSmMs4UgmSMhb55Mn9nB2H955lk2895vV>                                                                                |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Office:                  | 213C Tillman Hall                                                                                                                                         |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Classroom:               | 402 Tillman Hall                                                                                                                                          |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Instructor Office Hours: | M 2:00pm-4:00pm via Zoom at <https://clemson.zoom.us/j/91876861418?pwd=aZogrbrZXFsiITtCf0B2167qzXUOfK.1>                                                  |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Office Hours Calendar:   | <https://calendar.google.com/calendar/ical/03d02899ca3d2bd58a133223df6349a585cfad8b63bd51b09adef60fbf0edd43%40group.calendar.google.com/public/basic.ics> |
+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+

## Lecture and Class Files and Links

```{=html}
<style>
table {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}
</style>
```

+-----------+-----------------------------------------------------------------+:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| # Date    | # Topic                                                         | # Readings/Materials                                                                                                                                                                                                          |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8 Jan     | Introduction to Course/Descriptive Statistics and Linear Models | **Readings**                                                                                                                                                                                                                  |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   **None**                                                                                                                                                                                                                  |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | <hr>                                                                                                                                                                                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | \                                                                                                                                                                                                                             |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture01_Introduction/01_Basic_Statistics_and_LMs.pdf)             |
|           |                                                                 | -   [R Syntax](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture01_Introduction/01_Basic_Statistics_and_LMs.R)                                                                  |
|           |                                                                 | -   [R Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture01_Introduction/dataSexHeightWeight.rda)                                                                     |
|           |                                                                 | -   [Lecture Video (available after class)](https://www.youtube.com/playlist?list=PLSmMs4UgmSMhb55Mn9nB2H955lk2895vV)                                                                                                         |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15 Jan    | Make Friends with R                                             | **Readings**                                                                                                                                                                                                                  |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   **None**                                                                                                                                                                                                                  |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     <hr>                                                                                                                                                                                                                      |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture PDF](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture02_R/02_MakeFriendsWithR.pdf)                                   |
|           |                                                                 | -   [Lecture Quarto File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture02_R/02_MakeFriendsWithR.qmd)                                                                        |
|           |                                                                 | -   [R Syntax](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture02_R/02_MakeFriendsWithR.R)                                                                                     |
|           |                                                                 | -   [CSV Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture02_R/heights.csv)                                                                                          |
|           |                                                                 | -   [SAV Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture02_R/wide.sav)                                                                                             |
|           |                                                                 | -   [Lecture Video (available after class)](https://youtu.be/OmuH2FNF1bM)                                                                                                                                                     |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22 Jan    | Linear Model Interactions (Moderation)                          | **Reading**                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   **Required:** Hoffman (2015) Ch. 2                                                                                                                                                                                        |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | <hr>                                                                                                                                                                                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Video (watch before class)](https://youtu.be/k_qUAxmgOos)                                                                                                                                                        |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture03_Interactions/03_Linear_Model_Interactions_Moderation.pdf) |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [R Syntax](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture03_Interactions/03_Interactions.R)                                                                              |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [CSV Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture03_Interactions/03_InteractionsData.csv)                                                                   |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 29 Jan    | An Introduction to Estimation                                   | **Reading**                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   **Required:** Enders (2010) Ch. 3                                                                                                                                                                                         |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | <hr>                                                                                                                                                                                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Video (watch before class)](https://youtu.be/LDKtDvEi8sU)                                                                                                                                                        |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture04_Estimation/04%20Estimation%20Methods.pdf)                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   R Syntax Files                                                                                                                                                                                                            |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [Distributions](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture04_Estimation/04a%20Distributions.R)                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [Maximum Likelihood](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture04_Estimation/04b%20MaximumLikelihood.R)                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   R Data Files                                                                                                                                                                                                              |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [Statistics](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture04_Estimation/dataSexHeightWeight.rda)                                                                    |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 05 Feb    | Bayesian Estimation and Generalized Linear Models               | **Bayesian Estimation**                                                                                                                                                                                                       |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture04_Estimation/04%20Estimation%20Methods.pdf)                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Watch new portion of lecture video 04](https://youtu.be/NBsrk1Lg284)                                                                                                                                                     |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | <hr>                                                                                                                                                                                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Generalized Linear Models**                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Reading**                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   Azen & Walker (2011) Chs. 2 & 6                                                                                                                                                                                           |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Video (watch before class)](https://youtu.be/IWms55XNJKk)                                                                                                                                                        |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture05_Generalized/05_Generalized_Linear_Models.pdf)             |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   R Files                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Syntax File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture05_Generalized/05_Generalized_Linear_Models.R)                                                         |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Quarto Document File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture05_Generalized/05_Generalized_Linear_Models.qmd)                                              |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture05_Generalized/ologit.csv)                                                                                 |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12 Feb    | Regularization                                                  | **Reading**                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   Jacobucci, Grimm, & Zhang (2023) Ch. 4                                                                                                                                                                                    |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Video (watch before class)](https://youtu.be/qo5RzGvaEvM)                                                                                                                                                        |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://jonathantemplin.github.io/Multivariate-Modeling-Spring-2026/_lectures/06_Regularization/06_Regularization.html#/title-slide)                                                                     |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   R Files                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [Slides Quarto File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture06_Regularization/06_Regularization.qmd)                                                          |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Syntax File (for in-class example)](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture06_Regularization/06_Regularization.R)                                          |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19 Feb    | Matrix Algebra and the Multivariate Normal Distribution         | **Reading**                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   Johnson & Wichern (2002) Chs. 2-4                                                                                                                                                                                         |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | **Materials**                                                                                                                                                                                                                 |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Video (watch before class)](https://youtu.be/x7xCZ4HXWfE?si=p_OP9wX0fxOQ6_xX)                                                                                                                                    |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Multivariate-Modeling-Spring-2026/main/lectures/Lecture07_Matrix_Algebra_and_MVN/07_Matrix_Algebra_and_MVN.pdf)     |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 | -   R Files                                                                                                                                                                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Data File](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture07_Matrix_Algebra_and_MVN/dataSAT.rda)                                                                   |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Matrix Algebra Script](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture07_Matrix_Algebra_and_MVN/07_Matrix_Algebra.R)                                               |
|           |                                                                 |                                                                                                                                                                                                                               |
|           |                                                                 |     -   [R Multivariate Normal Distribution Script](https://github.com/jonathantemplin/Multivariate-Modeling-Spring-2026/blob/main/lectures/Lecture07_Matrix_Algebra_and_MVN/07_Multivariate_Normal_Distribution.R)           |
+-----------+-----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
