<!DOCTYPE html>
<html lang="en"><head>
<script src="13 Classification with Mixture Models_files/libs/clipboard/clipboard.min.js"></script>
<script src="13 Classification with Mixture Models_files/libs/quarto-html/tabby.min.js"></script>
<script src="13 Classification with Mixture Models_files/libs/quarto-html/popper.min.js"></script>
<script src="13 Classification with Mixture Models_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="13 Classification with Mixture Models_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="13 Classification with Mixture Models_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="13 Classification with Mixture Models_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <title>Classification Methods: Mixture Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="13 Classification with Mixture Models_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="13 Classification with Mixture Models_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="13 Classification with Mixture Models_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link rel="stylesheet" href="clemson.css">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="13 Classification with Mixture Models_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Classification Methods: Mixture Models</h1>
  <p class="subtitle">Latent Class &amp; Latent Profile Analysis</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="lecture-outline" class="slide level2">
<h2>Lecture Outline</h2>
<ul>
<li>Latent Class Analysis (LCA)
<ul>
<li>Underlying theory</li>
<li>Example analysis in R (<code>poLCA</code>)</li>
<li>Interpreting model parameters</li>
<li>Assessing model fit</li>
</ul></li>
<li>Latent Profile Analysis (LPA)
<ul>
<li>Underlying theory</li>
<li>Example analysis in R (<code>tidyLPA</code>)</li>
<li>Comparing class solutions</li>
</ul></li>
</ul>
</section>
<section>
<section id="overview" class="title-slide slide level1 center">
<h1>Overview</h1>

</section>
<section id="clusters-versus-classes" class="slide level2">
<h2>Clusters Versus Classes</h2>
<ul>
<li>When a researcher mentions cluster analysis, they often mean one of the following:
<ul>
<li>K-means clustering</li>
<li>Hierarchical clustering using distance methods</li>
<li>Discriminant analysis</li>
<li>Taxometrics</li>
</ul></li>
<li>Much less often, latent class analysis is included in the group
<ul>
<li>Although it is also useful for detecting clusters of observations</li>
</ul></li>
<li>For this lecture, we will consider <em>clusters</em> and <em>classes</em> to be synonymous
<ul>
<li>Clustering is often used to <em>find</em> clusters whereas classification is used to classify observations into known clusters</li>
</ul></li>
</ul>
</section>
<section id="lca-versus-other-methods" class="slide level2">
<h2>LCA Versus Other Methods</h2>
<ul>
<li>Although we use the terms classes and clusters synonymously, LCA differs from other methods</li>
<li><strong>LCA is a model-based method</strong> for clustering
<ul>
<li>LCA fits a statistical model to the data to determine classes</li>
</ul></li>
<li>Other methods (K-means, hierarchical) do not explicitly state a statistical model</li>
<li>Being model-based means we make <strong>explicit, testable assumptions</strong> about our data
<ul>
<li>Assumptions can be checked against the observed data</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="latent-class-analysis" class="title-slide slide level1 center">
<h1>Latent Class Analysis</h1>

</section>
<section id="section" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>Latent Class Analysis</p>
</div>
</section>
<section id="lca-introduction" class="slide level2">
<h2>LCA Introduction</h2>
<ul>
<li>Latent class models are commonly attributed to Lazarsfeld and Henry (1968)</li>
<li>The final number of classes is <strong>not predetermined</strong> prior to analysis
<ul>
<li>The number of classes is determined through comparison of fit statistics after fitting multiple models</li>
<li>The characteristics of each class are determined following the analysis</li>
<li>Similar to K-means and hierarchical clustering in this respect</li>
</ul></li>
</ul>
</section>
<section id="variable-types-used-in-lca" class="slide level2">
<h2>Variable Types Used in LCA</h2>
<ul>
<li>As originally conceived, LCA uses:
<ul>
<li>A set of <strong>binary-outcome variables</strong> — values coded as 0 or 1. Examples include:
<ul>
<li>Test items — scored correct (1) or incorrect (0)</li>
<li>True/false questions</li>
<li>Presence/absence indicators</li>
<li>Any other binary outcome</li>
</ul></li>
</ul></li>
<li>Extensions allow for <strong>ordered categorical</strong> or <strong>nominal</strong> indicators
<ul>
<li>This general form is still called LCA regardless of indicator type</li>
</ul></li>
</ul>
</section>
<section id="lca-process" class="slide level2">
<h2>LCA Process</h2>
<ul>
<li>For a specified number of classes, LCA estimates:
<ol type="1">
<li><strong>For each class:</strong> the probability that each indicator equals one <span class="math inline">\(\pi_{jc}\)</span></li>
<li><strong>For each observation:</strong> the probability of belonging to each class <span class="math inline">\(\alpha_{ic}\)</span>
<ul>
<li>These sum to 1 across classes for each person</li>
<li>This differs from K-means, where class membership is certain</li>
</ul></li>
<li><strong>Across observations:</strong> the overall probability that any observation is in each class <span class="math inline">\(\eta_c\)</span></li>
</ol></li>
</ul>
</section>
<section id="lca-estimation" class="slide level2">
<h2>LCA Estimation</h2>
<ul>
<li>LCA estimation differs from other clustering methods:
<ul>
<li>Hierarchical clustering creates new distance matrices at each step</li>
<li>K-means shifts cases between clusters using distance metrics</li>
<li><strong>LCA uses distributional assumptions</strong> to find classes — the distribution provides the measure of “distance”</li>
</ul></li>
<li>Estimation is performed via the <strong>Expectation-Maximization (EM) algorithm</strong>
<ul>
<li>E-step: compute posterior class probabilities</li>
<li>M-step: update model parameters to maximize log-likelihood</li>
<li>Iterate until convergence</li>
</ul></li>
<li><strong>Multiple random starting values</strong> are recommended to avoid local maxima</li>
</ul>
</section>
<section id="lca-distributional-assumptions" class="slide level2">
<h2>LCA Distributional Assumptions</h2>
<ul>
<li>Because LCA uses binary-outcome variables, it relies on a <strong>binary-outcome distribution</strong></li>
<li>Within each latent class, the variables are assumed to:
<ul>
<li>Be <strong>independent</strong> of one another (<em>Local Independence</em>)</li>
<li>Follow a <strong>Bernoulli distribution</strong> marginally:</li>
</ul></li>
</ul>
<p><span class="math display">\[f(x_i) = \left(\pi_i \right)^{x_i} \left(1-\pi_i\right)^{(1-x_i)}\]</span></p>
<ul>
<li>The Bernoulli distribution describes a single binary event — like flipping a coin with probability <span class="math inline">\(\pi\)</span> of heads</li>
</ul>
</section>
<section id="bernoulli-distribution-illustration" class="slide level2">
<h2>Bernoulli Distribution Illustration</h2>
<ul>
<li><p>Consider a single binary test item, <span class="math inline">\(X\)</span>:</p>
<ul>
<li>Let <span class="math inline">\(X = 1\)</span> if a student answers correctly, <span class="math inline">\(X = 0\)</span> if incorrect</li>
<li>Suppose the probability of a correct response is <span class="math inline">\(\pi = 0.75\)</span></li>
</ul></li>
<li><p>If <span class="math inline">\(X = 1\)</span>, the likelihood is: <span class="math display">\[f(x_i=1) = (0.75)^{1}(1-0.75)^{0} = 0.75\]</span></p></li>
<li><p>If <span class="math inline">\(X = 0\)</span>, the likelihood is: <span class="math display">\[f(x_i=0) = (0.75)^{0}(1-0.75)^{1} = 0.25\]</span></p></li>
<li><p>For discrete-outcome variables, the likelihood equals the probability of the event occurring</p></li>
</ul>
</section>
<section id="independent-bernoulli-variables" class="slide level2">
<h2>Independent Bernoulli Variables</h2>
<ul>
<li>For <strong>independent</strong> binary variables, the joint probability is the product of the individual probabilities:</li>
</ul>
<p><span class="math display">\[P(X_1=x_1, X_2=x_2,\ldots,X_J=x_J) = \prod_{j=1}^{J} \pi_j^{x_j} \left(1-\pi_j\right)^{\left(1-x_j\right)}\]</span></p>
<ul>
<li>In LCA, this independence assumption holds <strong>within each class</strong> (Local Independence)
<ul>
<li>Conditional on class membership, knowing one item response gives no additional information about another item response</li>
<li>Any association among observed variables is explained entirely by the latent class</li>
</ul></li>
</ul>
</section>
<section id="finite-mixture-models" class="slide level2">
<h2>Finite Mixture Models</h2>
<ul>
<li>LCA models are special cases of <strong>Finite Mixture Models (FMM)</strong></li>
<li>A finite mixture model expresses the distribution of <strong>X</strong> as a weighted sum of class-specific distributions:</li>
</ul>
<p><span class="math display">\[f(\textbf{X}) = \sum_{g=1}^G \eta_g f(\textbf{X}|g)\]</span></p>
<ul>
<li><span class="math inline">\(\eta_g\)</span> is the mixing proportion for class <span class="math inline">\(g\)</span> (must sum to 1)</li>
<li><span class="math inline">\(f(\textbf{X}|g)\)</span> is the class-specific distribution of <strong>X</strong></li>
<li>In LCA, <span class="math inline">\(f(\textbf{X}|g)\)</span> is a product of Bernoulli distributions (due to local independence)</li>
</ul>
</section>
<section id="latent-class-analysis-as-a-fmm" class="slide level2">
<h2>Latent Class Analysis as a FMM</h2>
<p>A latent class model for <span class="math inline">\(J\)</span> binary indicators (<span class="math inline">\(j = 1,\ldots,J\)</span>) with <span class="math inline">\(C\)</span> classes (<span class="math inline">\(c = 1,\ldots,C\)</span>):</p>
<p><span class="math display">\[f(\mathbf{x}_i) = \displaystyle {\sum_{c=1}^{C} \eta_c} \prod_{j=1}^{J} \pi_{jc}^{x_{ij}} \left(1-\pi_{jc}\right)^{1-x_{ij}}\]</span></p>
<ul>
<li><span class="math inline">\(\eta_c\)</span> — probability that any individual is in class <span class="math inline">\(c\)</span> (must sum to 1)</li>
<li><span class="math inline">\(x_{ij}\)</span> — observed binary response of individual <span class="math inline">\(i\)</span> to item <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\pi_{jc}\)</span> — probability of a positive response (<span class="math inline">\(x_{ij} = 1\)</span>) for class <span class="math inline">\(c\)</span> on item <span class="math inline">\(j\)</span></li>
</ul>
</section>
<section id="estimation-process" class="slide level2">
<h2>Estimation Process</h2>
<ul>
<li>Successfully applying LCA involves answering two key questions:
<ol type="1">
<li><strong>How many classes are present?</strong>
<ul>
<li>Fit LCA models with differing numbers of classes</li>
<li>Choose based on fit statistics (AIC, BIC, chi-square, entropy)</li>
</ul></li>
<li><strong>What does each class represent?</strong>
<ul>
<li>Inspect the item response probabilities (<span class="math inline">\(\hat{\pi}_{jc}\)</span>) for the best-fitting solution</li>
<li>Look for meaningful patterns distinguishing the classes</li>
</ul></li>
</ol></li>
</ul>
</section>
<section id="lca-in-r-the-polca-package" class="slide level2">
<h2>LCA in R: The <code>poLCA</code> Package</h2>
<ul>
<li>In R, the <strong><code>poLCA</code></strong> package (Linzer &amp; Lewis, 2011) fits LCA models
<ul>
<li>“<strong>P</strong>olytomous <strong>V</strong>ariable <strong>L</strong>atent <strong>C</strong>lass <strong>A</strong>nalysis”</li>
<li>Handles binary and polytomous (multi-category) indicators</li>
<li>Uses EM algorithm with multiple random starts</li>
</ul></li>
<li>Install: <code>install.packages("poLCA")</code></li>
</ul>
</section>
<section id="lca-in-r-the-polca-package-1" class="slide level2">
<h2>LCA in R: The <code>poLCA</code> Package</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Argument</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>formula</code></td>
<td><code>cbind(item1, item2, ...) ~ 1</code></td>
</tr>
<tr class="even">
<td><code>data</code></td>
<td>Data frame; <strong>item values must start at 1</strong>, not 0</td>
</tr>
<tr class="odd">
<td><code>nclass</code></td>
<td>Number of latent classes to estimate</td>
</tr>
<tr class="even">
<td><code>nrep</code></td>
<td>Number of random starting points (≥ 10 recommended)</td>
</tr>
<tr class="odd">
<td><code>verbose</code></td>
<td><code>FALSE</code> to suppress iteration output</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="lca-example" class="title-slide slide level1 center">
<h1>LCA Example</h1>

</section>
<section id="section-1" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>LCA Example #1</p>
</div>
</section>
<section id="lca-example-macready-dayton-1977" class="slide level2">
<h2>LCA Example: Macready &amp; Dayton (1977)</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Data discussed in Bartholomew and Knott (<em>Latent Variable Models and Factor Analysis</em>)</li>
<li>A four-item binary math test administered to <span class="math inline">\(N = 142\)</span> students</li>
<li>Macready and Dayton’s goal: classify students into two latent groups:
<ul>
<li><strong>Masters</strong> — students who have mastered the content</li>
<li><strong>Non-masters</strong> — students who have not mastered the content</li>
</ul></li>
<li>We will fit a <strong>2-class LCA model</strong> and interpret the results</li>
</ul>
</div><div class="column" style="width:40%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>u1</code></td>
<td>Math item 1 (0/1)</td>
</tr>
<tr class="even">
<td><code>u2</code></td>
<td>Math item 2 (0/1)</td>
</tr>
<tr class="odd">
<td><code>u3</code></td>
<td>Math item 3 (0/1)</td>
</tr>
<tr class="even">
<td><code>u4</code></td>
<td>Math item 4 (0/1)</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="lca-in-r-data-preparation" class="slide level2">
<h2>LCA in R: Data Preparation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  u1 u2 u3 u4
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2
6  2  2  2  2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2 
67 75 </code></pre>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><code>poLCA</code> requires each item’s values to be <strong>positive integers starting at 1</strong>. For binary items originally coded 0/1, add 1 to recode them as 1/2 before fitting.</p>
</div>
</div>
</div>
</section>
<section id="lca-in-r-fitting-the-2-class-model" class="slide level2">
<h2>LCA in R: Fitting the 2-Class Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$u1
           Pr(1)  Pr(2)
class 1:  0.7914 0.2086
class 2:  0.2466 0.7534

$u2
           Pr(1)  Pr(2)
class 1:  0.9317 0.0683
class 2:  0.2197 0.7803

$u3
           Pr(1)  Pr(2)
class 1:  0.9821 0.0179
class 2:  0.5684 0.4316

$u4
           Pr(1)  Pr(2)
class 1:  0.9477 0.0523
class 2:  0.2925 0.7075

Estimated class population shares 
 0.4134 0.5866 
 
Predicted class memberships (by modal posterior prob.) 
 0.4577 0.5423 
 
========================================================= 
Fit for 2 latent classes: 
========================================================= 
number of observations: 142 
number of estimated parameters: 9 
residual degrees of freedom: 6 
maximum log-likelihood: -331.7637 
 
AIC(2): 681.5273
BIC(2): 708.1298
G^2(2): 8.965682 (Likelihood ratio/deviance statistic) 
X^2(2): 9.459244 (Chi-square goodness of fit) 
 </code></pre>
</div>
</div>
<ul>
<li><code>nrep = 10</code> runs the algorithm 10 times with different random starts</li>
<li>The solution with the <strong>highest log-likelihood</strong> is retained</li>
<li>Increasing <code>nrep</code> reduces the chance of stopping at a local maximum</li>
</ul>
</section>
<section id="lca-parameter-information-types" class="slide level2">
<h2>LCA Parameter Information Types</h2>
<p>Three types of information from an LCA model:</p>
<ol type="1">
<li><strong>Class size estimates</strong> (<span class="math inline">\(\eta_c\)</span>)
<ul>
<li>Proportion of the population in each class</li>
</ul></li>
<li><strong>Item response probabilities</strong> (<span class="math inline">\(\pi_{jc}\)</span>)
<ul>
<li>Probability of a correct response to item <span class="math inline">\(j\)</span> for a person in class <span class="math inline">\(c\)</span></li>
</ul></li>
<li><strong>Posterior class probabilities</strong> (<span class="math inline">\(\alpha_{ic}\)</span>)
<ul>
<li>Probability that individual <span class="math inline">\(i\)</span> belongs to class <span class="math inline">\(c\)</span>, given their responses</li>
</ul></li>
</ol>
</section>
<section id="class-size-estimates-eta_c" class="slide level2">
<h2>Class Size Estimates (<span class="math inline">\(\eta_c\)</span>)</h2>
<p><strong>From <code>poLCA</code> output:</strong></p>
<pre><code>Estimated class population shares
 0.5866 0.4134

Predicted class memberships (modal posterior prob.)
 0.5423 0.4577</code></pre>
<ul>
<li><strong>Class 1:</strong> approximately <strong>58.7%</strong> of the population (<span class="math inline">\(\eta_1 = 0.587\)</span>)</li>
<li><strong>Class 2:</strong> approximately <strong>41.3%</strong> of the population (<span class="math inline">\(\eta_2 = 0.413\)</span>)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>“Population shares” come from the model. “Predicted memberships” assign each person to their most probable class — these will differ slightly from the model-estimated shares.</p>
</div>
</div>
</div>
</section>
<section id="item-response-probability-estimates-pi_jc" class="slide level2">
<h2>Item Response Probability Estimates (<span class="math inline">\(\pi_{jc}\)</span>)</h2>
<p><strong>From <code>poLCA</code> output</strong> (Pr(2) = probability of correct response):</p>
<pre><code>Conditional item response probabilities by class

$u1      Pr(1)  Pr(2)         $u2      Pr(1)  Pr(2)
 Class 1: 0.247  0.753          Class 1: 0.220  0.780
 Class 2: 0.791  0.209          Class 2: 0.932  0.068

$u3      Pr(1)  Pr(2)         $u4      Pr(1)  Pr(2)
 Class 1: 0.568  0.432          Class 1: 0.292  0.708
 Class 2: 0.982  0.018          Class 2: 0.948  0.052</code></pre>
<ul>
<li><code>Pr(2)</code> is the probability of a correct response (original code = 1)</li>
<li>Class 1 has <strong>high</strong> correct-response probabilities; Class 2 has <strong>very low</strong> probabilities</li>
</ul>
</section>
<section id="interpreting-the-classes" class="slide level2">
<h2>Interpreting the Classes</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Item</th>
<th style="text-align: center;">Class 1 <span class="math inline">\(\pi_{j1}\)</span></th>
<th style="text-align: center;">Class 2 <span class="math inline">\(\pi_{j2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">u1</td>
<td style="text-align: center;">0.753</td>
<td style="text-align: center;">0.209</td>
</tr>
<tr class="even">
<td style="text-align: center;">u2</td>
<td style="text-align: center;">0.780</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">u3</td>
<td style="text-align: center;">0.432</td>
<td style="text-align: center;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: center;">u4</td>
<td style="text-align: center;">0.708</td>
<td style="text-align: center;">0.052</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Class 1</strong> — high probability of correct response across all items
<ul>
<li><span class="math inline">\(\Rightarrow\)</span> <strong>Masters</strong>: students who have mastered the material</li>
</ul></li>
<li><strong>Class 2</strong> — very low probability of correct response across all items
<ul>
<li><span class="math inline">\(\Rightarrow\)</span> <strong>Non-masters</strong>: students who have not mastered the material</li>
</ul></li>
</ul>
</section>
<section id="visualizing-item-response-profiles" class="slide level2">
<h2>Visualizing Item Response Profiles</h2>

<img data-src="13-Classification-with-Mixture-Models_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section></section>
<section>
<section id="assessing-model-fit" class="title-slide slide level1 center">
<h1>Assessing Model Fit</h1>

</section>
<section id="section-2" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>Assessing Model Fit</p>
</div>
</section>
<section id="approaches-to-assessing-lca-fit" class="slide level2">
<h2>Approaches to Assessing LCA Fit</h2>
<ul>
<li>No single definitive approach — use multiple measures together:
<ul>
<li><strong>Absolute fit</strong>: model-based <span class="math inline">\(\chi^2\)</span> tests</li>
<li><strong>Relative fit</strong>: information criteria (AIC, BIC)</li>
<li><strong>Classification quality</strong>: entropy</li>
</ul></li>
<li>The goal is to identify a parsimonious, substantively meaningful solution</li>
</ul>
</section>
<section id="model-chi-squared-test" class="slide level2">
<h2>Model Chi-Squared Test</h2>
<ul>
<li>The <span class="math inline">\(\chi^2\)</span> test compares <strong>observed</strong> response pattern frequencies to <strong>model-expected</strong> frequencies</li>
<li>For <span class="math inline">\(J\)</span> binary items, there are <span class="math inline">\(p = 2^J\)</span> possible response patterns</li>
<li>Degrees of freedom = number of response patterns <span class="math inline">\(-\)</span> model parameters <span class="math inline">\(-\)</span> 1</li>
<li>The Pearson statistic:</li>
</ul>
<p><span class="math display">\[\chi^2_p = \sum_r \frac{(O_r - E_r)^2}{E_r}\]</span></p>
</section>
<section id="model-chi-squared-test-limitations" class="slide level2">
<h2>Model Chi-Squared Test Limitations</h2>
<ul>
<li><p>For <span class="math inline">\(J\)</span> binary items, there are <span class="math inline">\(2^J\)</span> possible response patterns</p></li>
<li><p><strong>Limitation:</strong> invalid when many cells have small expected frequencies</p>
<ul>
<li>With <span class="math inline">\(J = 4\)</span> items: 16 patterns — feasible</li>
<li>With <span class="math inline">\(J = 20\)</span> items: over 1 million patterns — infeasible</li>
</ul></li>
</ul>
</section>
<section id="chi-squared-in-r" class="slide level2">
<h2>Chi-Squared in R</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.459244</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.965682</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1493499</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1755173</code></pre>
</div>
</div>
<p><strong>Results for the Macready &amp; Dayton 2-class solution:</strong></p>
<pre><code>Pearson chi-square (df = 6):  9.459   p = 0.149
G-squared       (df = 6):     8.966   p = 0.176</code></pre>
<p>Neither test is significant — the 2-class model fits the data adequately.</p>
</section>
<section id="log-likelihood" class="slide level2">
<h2>Log Likelihood</h2>
<ul>
<li>The <strong>log-likelihood</strong> measures how well the model reproduces the observed data:</li>
</ul>
<p><span class="math display">\[\log L = \sum_{k=1}^N \log \left( {\sum_{c=1}^{C} \eta_c} \prod_{j=1}^{J} \pi_{jc}^{x_{kj}} \left(1-\pi_{jc}\right)^{1-x_{kj}} \right)\]</span></p>
</section>
<section id="information-criteria" class="slide level2">
<h2>Information Criteria</h2>
<ul>
<li>The <strong>AIC</strong> and <strong>BIC</strong> penalize the log-likelihood for model complexity:</li>
</ul>
<p><span class="math display">\[AIC = 2q - 2\log L \qquad BIC = q\log(N) - 2\log L\]</span></p>
<ul>
<li><span class="math inline">\(q\)</span> = number of free parameters; <span class="math inline">\(N\)</span> = sample size</li>
<li><strong>Lower values indicate better fit</strong> (for comparing models with the same data)</li>
</ul>
</section>
<section id="comparing-models-in-r" class="slide level2">
<h2>Comparing Models in R</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Classes Parameters LogL AIC BIC
1       1          4 -375 759 770
2       2          9 -332 682 708
3       3         14 -329 687 728</code></pre>
</div>
</div>
</section>
<section id="information-criteria-model-comparison" class="slide level2">
<h2>Information Criteria: Model Comparison</h2>
<p><strong>Fit statistics for the Macready &amp; Dayton data:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Classes</th>
<th style="text-align: center;">Parameters</th>
<th style="text-align: center;">Log L</th>
<th style="text-align: center;">AIC</th>
<th style="text-align: center;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">−373.04</td>
<td style="text-align: center;">754.08</td>
<td style="text-align: center;">766.16</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;"><strong>9</strong></td>
<td style="text-align: center;"><strong>−331.76</strong></td>
<td style="text-align: center;"><strong>681.53</strong></td>
<td style="text-align: center;"><strong>708.13</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">−331.49</td>
<td style="text-align: center;">690.97</td>
<td style="text-align: center;">733.10</td>
</tr>
</tbody>
</table>
<ul>
<li>Both AIC and BIC are <strong>lowest for the 2-class solution</strong> ✓</li>
<li>Adding a third class provides minimal improvement in log-likelihood</li>
<li><strong>The 2-class model is preferred</strong> — consistent with Macready and Dayton’s hypothesis</li>
</ul>
</section>
<section id="entropy" class="slide level2">
<h2>Entropy</h2>
<ul>
<li><strong>Entropy</strong> measures how clearly each observation is classified into a class</li>
<li>Based on posterior class probabilities (<span class="math inline">\(\hat{\alpha}_{ic}\)</span>)</li>
<li>The <strong>relative entropy</strong> (scaled to <span class="math inline">\([0, 1]\)</span>):
<ul>
<li><strong>E near 1</strong>: high classification certainty (each person clearly belongs to one class)</li>
<li><strong>E near 0</strong>: high uncertainty (posterior probabilities are diffuse across classes)</li>
</ul></li>
</ul>
<p><span class="math display">\[E = 1 - \frac{-\displaystyle\sum_{i=1}^N \sum_{c=1}^C \hat{\alpha}_{ic} \log \hat{\alpha}_{ic}}{N \log C}\]</span></p>
</section>
<section id="computing-entropy-in-r" class="slide level2">
<h2>Computing Entropy in R</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Relative Entropy (2-class): 0.754</code></pre>
</div>
</div>
<ul>
<li>Entropy of 0.754 indicates <strong>good classification quality</strong></li>
<li>Most students are clearly classified as masters or non-masters</li>
</ul>
</section></section>
<section>
<section id="latent-profile-analysis" class="title-slide slide level1 center">
<h1>Latent Profile Analysis</h1>

</section>
<section id="section-3" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>Latent Profile Analysis</p>
</div>
</section>
<section id="lpa-introduction" class="slide level2">
<h2>LPA Introduction</h2>
<ul>
<li>Latent Profile Analysis (LPA) is the <strong>continuous-variable analog to LCA</strong>
<ul>
<li>Also attributed to Lazarsfeld and Henry (1968)</li>
</ul></li>
<li>Uses a set of <strong>continuous variables</strong> rather than binary indicators</li>
<li>The estimation process is the same: EM algorithm with multiple random starts</li>
<li>The key difference: <strong>normal (Gaussian) distributions</strong> replace Bernoulli distributions within each class</li>
</ul>
</section>
<section id="lpa-process" class="slide level2">
<h2>LPA Process</h2>
<ul>
<li>For a specified number of classes, LPA estimates:
<ol type="1">
<li><strong>For each class:</strong> the mean (<span class="math inline">\(\mu_{jc}\)</span>) and variance (<span class="math inline">\(\sigma^2_{jc}\)</span>) for each variable</li>
<li><strong>For each observation:</strong> the probability of belonging to each class <span class="math inline">\(\alpha_{ic}\)</span>
<ul>
<li>These sum to 1 across classes for each person</li>
</ul></li>
<li><strong>Across observations:</strong> the overall class proportions <span class="math inline">\(\eta_c\)</span></li>
</ol></li>
<li>The same three types of information as LCA:
<ul>
<li>Class sizes, class-specific parameters, and posterior probabilities</li>
</ul></li>
</ul>
</section>
<section id="lpa-distributional-assumptions" class="slide level2">
<h2>LPA Distributional Assumptions</h2>
<ul>
<li>Within each latent class, the variables are assumed to:
<ul>
<li>Be <strong>independent</strong> (local independence assumption, same as LCA)</li>
<li>Follow a <strong>normal distribution</strong> marginally:</li>
</ul></li>
</ul>
<p><span class="math display">\[f(x_i) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left(\frac{-(x_i - \mu)^2}{2\sigma^2}\right)\]</span></p>
</section>
<section id="lpa-distributional-assumptions-1" class="slide level2">
<h2>LPA Distributional Assumptions</h2>
<ul>
<li>Different classes have different means — and possibly different variances</li>
<li>The <strong>variance structure</strong> across classes is an important modeling choice:
<ul>
<li><strong>Equal variances</strong> across classes (more parsimonious, common default)</li>
<li><strong>Unequal variances</strong> (more flexible, more parameters to estimate)</li>
</ul></li>
</ul>
</section>
<section id="multivariate-normal-distribution" class="slide level2">
<h2>Multivariate Normal Distribution</h2>
<ul>
<li>Because LPA assumes independent normal variables within each class, the joint within-class distribution is <strong>multivariate normal (MVN)</strong> with a <em>diagonal</em> covariance matrix</li>
</ul>
<p><span class="math display">\[f(\textbf{x}) = \frac{1}{(2\pi)^{p/2}|\boldsymbol{\Sigma}|^{1/2}} \exp\left(-\frac{(\textbf{x}-\boldsymbol{\mu})^T\boldsymbol{\Sigma}^{-1}(\textbf{x}-\boldsymbol{\mu})}{2}\right)\]</span></p>
<ul>
<li><span class="math inline">\(\boldsymbol{\mu}\)</span> = class mean vector</li>
<li><span class="math inline">\(\boldsymbol{\Sigma}\)</span> = covariance matrix (<strong>diagonal</strong> for standard LPA — no within-class correlations)</li>
<li>Standard notation: <span class="math inline">\(\mathbf{x} \sim N_p(\boldsymbol{\mu}, \boldsymbol{\Sigma})\)</span></li>
</ul>
</section>
<section id="within-class-covariance-structure" class="slide level2">
<h2>Within-Class Covariance Structure</h2>
<ul>
<li>In standard LPA, within-class covariance is <strong>zero</strong> (local independence):
<ul>
<li>Knowing one variable gives no additional information about another, given class</li>
</ul></li>
<li>When within-class covariance is <strong>non-zero</strong>:
<ul>
<li>Contours become <strong>tilted ellipses</strong></li>
</ul></li>
<li>The <strong>local independence assumption</strong> can be checked:
<ul>
<li>Fit a model that allows within-class covariances and compare fit via AIC/BIC</li>
<li>Persistent residual correlations within classes suggest the assumption is violated</li>
</ul></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>If you suspect within-class correlations, try <code>variances = "equal", covariances = "equal"</code> (Model 2) and compare fit statistics to Model 1.</p>
</div>
</div>
</div>
</section>
<section id="lpa-as-a-finite-mixture-model" class="slide level2">
<h2>LPA as a Finite Mixture Model</h2>
<p>A latent profile model for <span class="math inline">\(J\)</span> continuous variables <span class="math inline">\((j = 1,\ldots,J)\)</span> with <span class="math inline">\(C\)</span> classes (<span class="math inline">\(c = 1,\ldots,C\)</span>):</p>
<p><span class="math display">\[f(\mathbf{x}_i) = \displaystyle {\sum_{c=1}^{C} \eta_c} \prod_{j=1}^{J} \frac{1}{\sqrt{2\pi\sigma^2_{jc}}} \exp\left(\frac{-(x_{ij} - \mu_{jc})^2}{2\sigma^2_{jc}}\right)\]</span></p>
<ul>
<li><span class="math inline">\(\eta_c\)</span> — class proportion (must sum to 1)</li>
<li><span class="math inline">\(\mu_{jc}\)</span> — mean of variable <span class="math inline">\(j\)</span> in class <span class="math inline">\(c\)</span></li>
<li><span class="math inline">\(\sigma^2_{jc}\)</span> — variance of variable <span class="math inline">\(j\)</span> in class <span class="math inline">\(c\)</span></li>
</ul>
</section>
<section id="lpa-in-r-the-tidylpa-package" class="slide level2">
<h2>LPA in R: The <code>tidyLPA</code> Package</h2>
<ul>
<li>In R, the <strong><code>tidyLPA</code></strong> package (Rosenberg et al., 2018) fits LPA models
<ul>
<li>Wraps the <code>mclust</code> package with a cleaner interface</li>
<li>Install: <code>install.packages("tidyLPA")</code></li>
</ul></li>
</ul>
</section>
<section id="lpa-in-r-the-tidylpa-package-1" class="slide level2">
<h2>LPA in R: The <code>tidyLPA</code> Package</h2>
<table class="caption-top">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>estimate_profiles()</code></td>
<td>Fits one or more LPA models</td>
</tr>
<tr class="even">
<td><code>get_fit()</code></td>
<td>Extracts fit statistics (log L, AIC, BIC, entropy)</td>
</tr>
<tr class="odd">
<td><code>get_estimates()</code></td>
<td>Extracts class-specific means and variances</td>
</tr>
<tr class="even">
<td><code>get_data()</code></td>
<td>Returns data with posterior probabilities and class assignments</td>
</tr>
<tr class="odd">
<td><code>plot_profiles()</code></td>
<td>Creates a class profile plot</td>
</tr>
</tbody>
</table>
</section>
<section id="lpa-variance-model-options" class="slide level2">
<h2>LPA Variance Model Options</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Model</th>
<th style="text-align: center;">Variances</th>
<th style="text-align: center;">Covariances</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1 (default)</td>
<td style="text-align: center;">Equal across classes</td>
<td style="text-align: center;">Zero (diagonal)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">Equal across classes</td>
<td style="text-align: center;">Equal across classes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><strong>Varying</strong> across classes</td>
<td style="text-align: center;">Zero (diagonal)</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Model 1</strong> matches the standard LPA assumption: equal variances, no within-class covariances</li>
</ul>
</section>
<section id="lpa-variance-model-options-1" class="slide level2">
<h2>LPA Variance Model Options</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Model</th>
<th style="text-align: center;">Variances</th>
<th style="text-align: center;">Covariances</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;"><strong>Varying</strong> across classes</td>
<td style="text-align: center;"><strong>Varying</strong> across classes</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">Equal across classes</td>
<td style="text-align: center;"><strong>Varying</strong> across classes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;"><strong>Varying</strong> across classes</td>
<td style="text-align: center;">Equal across classes</td>
</tr>
</tbody>
</table>
<ul>
<li>More complex models add parameters; use information criteria to compare</li>
</ul>
</section></section>
<section>
<section id="lpa-example" class="title-slide slide level1 center">
<h1>LPA Example</h1>

</section>
<section id="section-4" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>LPA Example: Fisher’s Iris Data</p>
</div>
</section>
<section id="lpa-example-fishers-iris-data" class="slide level2">
<h2>LPA Example: Fisher’s Iris Data</h2>
<ul>
<li>Fisher (1936) introduced a dataset of measurements on 150 iris flowers</li>
<li>Four continuous measurements per flower:</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>x1</td>
<td>Sepal length (cm)</td>
</tr>
<tr class="even">
<td>x2</td>
<td>Sepal width (cm)</td>
</tr>
<tr class="odd">
<td>x3</td>
<td>Petal length (cm)</td>
</tr>
<tr class="even">
<td>x4</td>
<td>Petal width (cm)</td>
</tr>
</tbody>
</table>
</section>
<section id="lpa-example-fishers-iris-data-1" class="slide level2">
<h2>LPA Example: Fisher’s Iris Data</h2>
<ul>
<li>Three species: <em>Iris setosa</em>, <em>I. versicolor</em>, <em>I. virginica</em> (50 flowers each; <span class="math inline">\(N = 150\)</span>)</li>
<li>We treat species membership as <strong>unknown</strong> and attempt to recover it via LPA</li>
</ul>
</section>
<section id="lpa-in-r-loading-data-and-fitting-models" class="slide level2">
<h2>LPA in R: Loading Data and Fitting Models</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 20
  Model Classes LogLik parameters     n   AIC   AWE   BIC  CAIC   CLC   KIC
  &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1       2  -489.         13   150 1004. 1145. 1043. 1056.  980. 1020.
2     1       3  -361.         18   150  759.  955.  813.  831.  725.  780.
3     1       4  -356.         23   150  758. 1010.  827.  850.  714.  784.
# ℹ 9 more variables: SABIC &lt;dbl&gt;, ICL &lt;dbl&gt;, Entropy &lt;dbl&gt;, prob_min &lt;dbl&gt;,
#   prob_max &lt;dbl&gt;, n_min &lt;dbl&gt;, n_max &lt;dbl&gt;, BLRT_val &lt;dbl&gt;, BLRT_p &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>variances = "equal"</code> and <code>covariances = "zero"</code> specify Model 1 — equal variances across classes, no within-class covariances. This is the standard LPA assumption.</p>
</div>
</div>
</div>
</section>
<section id="model-comparison" class="slide level2">
<h2>Model Comparison</h2>
<p><strong>Fit statistics for the Iris LPA (Model 1):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Classes</th>
<th style="text-align: center;">Parameters</th>
<th style="text-align: center;">Log L</th>
<th style="text-align: center;">AIC</th>
<th style="text-align: center;">BIC</th>
<th style="text-align: center;">Entropy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">−488.92</td>
<td style="text-align: center;">1003.83</td>
<td style="text-align: center;">1042.97</td>
<td style="text-align: center;">0.991</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"><strong>−361.43</strong></td>
<td style="text-align: center;"><strong>758.85</strong></td>
<td style="text-align: center;"><strong>813.04</strong></td>
<td style="text-align: center;"><strong>0.957</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">−310.12</td>
<td style="text-align: center;">666.23</td>
<td style="text-align: center;">735.48</td>
<td style="text-align: center;">0.945</td>
</tr>
</tbody>
</table>
<ul>
<li>AIC and BIC both favor the <strong>4-class solution</strong></li>
<li>But the data were generated from <strong>exactly 3 species</strong></li>
<li>This illustrates a known problem with information criteria in mixture modeling:
<ul>
<li>They can favor over-extraction (more classes than truly exist)</li>
<li><strong>Substantive knowledge and external validation are essential</strong></li>
</ul></li>
<li>We select the <strong>3-class solution</strong> based on prior knowledge</li>
</ul>
</section>
<section id="fitting-the-3-class-model" class="slide level2">
<h2>Fitting the 3-Class Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 8
   Category  Parameter Estimate      se        p Class Model Classes
   &lt;chr&gt;     &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1 Means     x1          5.01   0.0508  0            1     1       3
 2 Means     x2          3.43   0.0535  0            1     1       3
 3 Means     x3          1.46   0.0218  0            1     1       3
 4 Means     x4          0.246  0.0155  7.87e-57     1     1       3
 5 Variances x1          0.235  0.0261  2.38e-19     1     1       3
 6 Variances x2          0.107  0.0143  6.57e-14     1     1       3
 7 Variances x3          0.187  0.0254  1.82e-13     1     1       3
 8 Variances x4          0.0379 0.00572 3.39e-11     1     1       3
 9 Means     x1          5.92   0.0750  0            2     1       3
10 Means     x2          2.75   0.0443  0            2     1       3
# ℹ 14 more rows</code></pre>
</div>
</div>
</section>
<section id="fitting-the-3-class-model-1" class="slide level2">
<h2>Fitting the 3-Class Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  model_number classes_number    x1    x2    x3    x4 CPROB1   CPROB2   CPROB3
         &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1            1              3   5.1   3.5   1.4   0.2      1 5.37e-20 3.72e-44
2            1              3   4.9   3     1.4   0.2      1 5.82e-19 5.84e-44
3            1              3   4.7   3.2   1.3   0.2      1 1.63e-20 7.19e-46
4            1              3   4.6   3.1   1.5   0.2      1 4.45e-19 4.35e-44
5            1              3   5     3.6   1.4   0.2      1 1.94e-20 1.25e-44
6            1              3   5.4   3.9   1.7   0.4      1 4.69e-16 8.18e-37
# ℹ 1 more variable: Class &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="the-3-class-solution-class-sizes" class="slide level2">
<h2>The 3-Class Solution: Class Sizes</h2>
<p><strong>From <code>get_fit()</code> output:</strong></p>
<pre><code>FINAL CLASS COUNTS AND PROPORTIONS
   Class 1:  50.000  (0.333)
   Class 2:  54.888  (0.366)
   Class 3:  45.112  (0.301)</code></pre>
<ul>
<li>Three approximately equal classes, consistent with the true species distribution (50 per species)</li>
<li>The model has correctly identified the rough size structure</li>
</ul>
</section>
<section id="the-3-class-solution-class-means" class="slide level2">
<h2>The 3-Class Solution: Class Means</h2>
<p><strong>Class-specific means from <code>get_estimates()</code>:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Class 1</th>
<th style="text-align: center;">Class 2</th>
<th style="text-align: center;">Class 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">x1 (Sepal Length)</td>
<td style="text-align: center;">5.01</td>
<td style="text-align: center;">5.92</td>
<td style="text-align: center;">6.68</td>
</tr>
<tr class="even">
<td style="text-align: left;">x2 (Sepal Width)</td>
<td style="text-align: center;">3.43</td>
<td style="text-align: center;">2.75</td>
<td style="text-align: center;">3.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x3 (Petal Length)</td>
<td style="text-align: center;">1.46</td>
<td style="text-align: center;">4.33</td>
<td style="text-align: center;">5.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">x4 (Petal Width)</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">1.35</td>
<td style="text-align: center;">2.07</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Class 1</strong>: Very small petals, wide sepals → <em>Iris setosa</em></li>
<li><strong>Class 2</strong>: Medium-sized flowers, narrower sepals → <em>Iris versicolor</em></li>
<li><strong>Class 3</strong>: Largest petals and sepals → <em>Iris virginica</em></li>
</ul>
</section>
<section id="visualizing-class-profiles" class="slide level2">
<h2>Visualizing Class Profiles</h2>

<img data-src="13-Classification-with-Mixture-Models_files/figure-revealjs/unnamed-chunk-10-1.png" width="960" class="r-stretch"></section>
<section id="visualizing-class-profiles-1" class="slide level2">
<h2>Visualizing Class Profiles</h2>

<img data-src="13-Classification-with-Mixture-Models_files/figure-revealjs/unnamed-chunk-11-1.png" width="960" class="r-stretch"></section>
<section id="evaluating-classification-quality" class="slide level2">
<h2>Evaluating Classification Quality</h2>
<pre><code>Class 1  Class 2  Class 3
  1.000    0.970    0.966</code></pre>
<ul>
<li>Class 1 (setosa) is perfectly separated from the others</li>
<li>Classes 2 and 3 have 3–4% overlap — the two larger species are harder to distinguish</li>
<li>Matches the known botanical overlap between <em>versicolor</em> and <em>virginica</em></li>
</ul>
</section></section>
<section>
<section id="concluding-remarks" class="title-slide slide level1 center">
<h1>Concluding Remarks</h1>

</section>
<section id="section-5" class="slide level2 center">
<h2></h2>
<div style="text-align: center; font-size: 2em;">
<p>Concluding Remarks</p>
</div>
</section>
<section id="lca-vs.-lpa-comparison" class="slide level2">
<h2>LCA vs.&nbsp;LPA: Comparison</h2>
<table class="caption-top">
<colgroup>
<col style="width: 47%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">LCA</th>
<th style="text-align: left;">LPA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Indicator type</td>
<td style="text-align: left;">Binary / categorical</td>
<td style="text-align: left;">Continuous</td>
</tr>
<tr class="even">
<td style="text-align: left;">Within-class distribution</td>
<td style="text-align: left;">Bernoulli</td>
<td style="text-align: left;">Normal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class parameters</td>
<td style="text-align: left;">Item probabilities (<span class="math inline">\(\pi_{jc}\)</span>)</td>
<td style="text-align: left;">Means (<span class="math inline">\(\mu_{jc}\)</span>) and variances (<span class="math inline">\(\sigma^2_{jc}\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">R package</td>
<td style="text-align: left;"><code>poLCA</code></td>
<td style="text-align: left;"><code>tidyLPA</code></td>
</tr>
</tbody>
</table>
</section>
<section id="extensions-of-these-methods" class="slide level2">
<h2>Extensions of These Methods</h2>
<ul>
<li>Many extensions exist in recent empirical research:
<ul>
<li><strong>Growth Mixture Models</strong> — detect groups with differing growth trajectories over time</li>
<li><strong>Diagnostic Classification Models</strong> — confirmatory LCA specifying class characteristics <em>prior</em> to analysis; used in psychological and educational testing</li>
<li><strong>Mixture IRT Models</strong> — combine item response theory with latent class structure</li>
<li><strong>Mixture Regression Models</strong> — latent classes defined by distinct regression relationships</li>
<li><strong>General Finite Mixture Models</strong> — virtually any statistical distribution can form a mixture model</li>
</ul></li>
</ul>
</section>
<section id="concluding-remarks-1" class="slide level2">
<h2>Concluding Remarks</h2>
<ul>
<li>LCA and LPA are <strong>model-based techniques</strong> for identifying latent clusters</li>
<li>Both methods make explicit, testable assumptions about the data</li>
<li>Key practical challenges:
<ul>
<li>The number of classes must be inferred — no single definitive criterion</li>
<li>Information criteria often favor <strong>over-extraction</strong> (too many classes)</li>
<li>Multiple local maxima are possible — always use many random starts (<code>nrep</code>)</li>
</ul></li>
<li><strong>Use these methods carefully</strong> — they are exploratory and prone to spurious findings
<ul>
<li>Validate results with substantive knowledge</li>
<li>Seek convergence across multiple fit indices</li>
<li>Replicate with independent samples when possible</li>
</ul></li>
</ul>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<ul>
<li>Lazarsfeld, P. F. &amp; Henry, N. W. (1968). <em>Latent structure analysis</em>. Houghton Mifflin.</li>
<li>Linzer, D. A. &amp; Lewis, J. B. (2011). poLCA: An R package for polytomous variable latent class analysis. <em>Journal of Statistical Software, 42</em>(10), 1–29.</li>
<li>Macready, G. B. &amp; Dayton, C. M. (1977). The use of probabilistic models in the assessment of mastery. <em>Journal of Educational Statistics, 2</em>(2), 99–120.</li>
<li>Rosenberg, J. M., van Lissa, C. J., Beymer, P. N., Anderson, D. J., Schell, M. J., &amp; Schmidt, J. A. (2018). tidyLPA: An R package to easily carry out latent profile analysis (LPA). <em>Journal of Open Source Software, 3</em>(30), 978.</li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="clemson_coe.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="13 Classification with Mixture Models_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>